# -------- BUILD STAGE --------
FROM maven:3.9.9-eclipse-temurin-17 AS builder
WORKDIR /app   
COPY pom.xml .
RUN mvn -B -q -DskipTests dependency:go-offline
COPY src ./src
RUN mvn clean package -DskipTests
# -------- RUNTIME STAGE --------
FROM eclipse-temurin:17-jre-jammy
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar
EXPOSE 8080    
ENTRYPOINT ["java","-jar","/app/app.jar"]
