pipeline {
    agent any

    environment {
        DOCKERHUB_USER = "bnalbant"
        IMAGE_NAME = "mercedes-cicd"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout https://github.com/yigitnalbant/ci-cd_training.git
            }
        }

        stage('Set Image Name by Branch') {
            steps {
                script {

                    if (env.BRANCH_NAME == "test") {
                        env.IMAGE_NAME = "mercedes-cicd-test"
                    }

                    if (env.BRANCH_NAME == "prod") {
                        env.IMAGE_NAME = "mercedes-cicd-prod"
                    }

                    echo "Branch: ${env.BRANCH_NAME}"
                    echo "Image: ${DOCKERHUB_USER}/${IMAGE_NAME}"
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh """
                docker build -t ${DOCKERHUB_USER}/${IMAGE_NAME}:${IMAGE_TAG} .
                """
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-bnalbant',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh """
                    echo \$DOCKER_PASS | docker login -u \$DOCKER_USER --password-stdin
                    """
                }
            }
        }

        stage('Push Image') {
            steps {
                sh """
                docker push ${DOCKERHUB_USER}/${IMAGE_NAME}:${IMAGE_TAG}
                """
            }
        }
    }

    post {
        success {
            echo "Docker image başarıyla push edildi"
        }

        failure {
            echo "Pipeline hata verdi"
        }
    }
}
