name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: eu-central-1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: AWS Login
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::346568123151:role/github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Get Terraform Outputs
        id: tf_outputs
        working-directory: terraform
        run: |
          echo "bucket=$(terraform output -raw bucket_name)" >> $GITHUB_OUTPUT

      - name: Build App
        working-directory: app
        run: |
          npm install
          npm run build || echo "no build step"

      - name: Deploy to S3
        run: |
          aws s3 sync app/ s3://${{ steps.tf_outputs.outputs.bucket }} --delete
:::
